#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DriveFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     DriveBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     ArmL,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     ArmR,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    cube,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "TeleOp_functions.h"
#include "autonomous_functions.h"
#include "Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-sensormux.h"


const tMUXSensor USonic = msensor_S4_1;
const tMUXSensor Colr = msensor_S4_2;

const tMotor DriveMotors[] = { DriveFL, DriveFR, DriveBL, DriveBR };

void initializeRobot() {

}

task main()
{
	initializeRobot();
	waitForStart(); // Wait for the beginning of autonomous phase.

	//IR/RAMP AUTONOMOUS L-R
	//|\
	//|  \
	//|    \
	//|-|    \
	//| |      \
	//| |        \
	//| |        /
	//| |      /
	//|-|   R/
	//|    /
	//|  /
	//|/
	//start back agains with wall
	//rotate 45* right
	//scan IR
	//move L until white line
	//backup onto ramp

	//IR/RAMP AUTONOMOUS R-L
	//|\
	//|  \
	//|    \
	//|-|   R\
	//| |      \
	//| |        \
	//| |        /
	//| |      /
	//|-|    /
	//|    /
	//|  /
	//|/
	//start back against wall
	//rotate 45* left
	//scan IR
	//move R until white line
	//backup onto ramp

	//RAMP AUTONOMOUS LEFT
	//|\
	//|  \
	//|    \
	//|-|    \
	//| |      \
	//| |        \
	//| |        /
	//| |      /
	//|-|   R/
	//|    /
	//|  /
	//|/
	//start back against wall
	//rotate 45* left
	//forward until white line
	//turn 90* left
	//backup onto ramp

	//RAMP AUTONOMOUS RIGHT
	//|\
	//|  \
	//|    \
	//|-|   R\
	//| |      \
	//| |        \
	//| |        /
	//| |      /
	//|-|    /
	//|    /
	//|  /
	//|/
	//start back against wall
	//rotate 45* right
	//forward until white line
	//turn 90* right
	//backup onto ramp
}
