#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DriveFR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DriveBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "TeleOp_functions.h"
#include "JoystickDriver.c"

const tMotor DriveMotors[] = { DriveFL, DriveFR, DriveBL, DriveBR };

task main() {
	waitForStart();
	while (true) {
		arcade_drive(DriveMotors, 4);
		getJoystickSettings(joystick);

		if(joy1Btn(6) == true) {
			motor[Flag] = 50;
		}
		if(joy1Btn(8) == true) {
			motor[Flag] = -50;
		}
		else {
			motor[Flag] = 0;
		}
	}
}
