#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DriveFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     DriveBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    cube,                 BadType)
#pragma config(Servo,  srvo_S1_C4_2,    hand,                 BadType)
#pragma config(Servo,  srvo_S1_C4_3,    hand2,                BadType)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               BadType)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               BadType)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               BadType)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "TeleOp_functions.h"
#include "autonomous_functions.h"

const tMotor DriveMotors[] = { DriveFL, DriveFR, DriveBL, DriveBR };

task main()
{
	waitForStart();

	motor[Arm] = -50;
	//servo[hand] = 90;
	//servo[hand2] = 180-ServoValue[hand];
	wait1Msec(750);
	motor[Arm] = 0;

	omnimove_for_length_time(1500, DriveMotors);
}
