#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     LEGOLIGHT,             sensorLightActive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DriveBL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DriveFR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     FRM,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     EG1,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     EG2,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    USServo,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    autoArm,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "TeleOp_functions.h"  // an H file that we wrote implementing various functions
#include "autonomous_functions.h"	// an H file that we wrote implementing various functions


const tMotor DriveMotors[] = { DriveFL, DriveBL, DriveFR, DriveBR };  //an array that describes the Drive motors
const int N_MOTORS = 4;


int SERVO_DEGREES_FRONT = 0;

void  ZeroEncoders ()
{ for (int i = 0; i < N_MOTORS; ++i)
		nMotorEncoder[DriveMotors[i]] = 0;
}

int   EncoderTicks ()
{ int sum = 0;
	for (int i = 0; i < N_MOTORS; ++i)
		sum += abs(nMotorEncoder[DriveMotors[i]]);
	return sum;
}


void Drive(int fl, int fr, int br, int bl) {
	motor[DriveFL] = fl;
	motor[DriveFR] = fr;
	motor[DriveBR] = br;
	motor[DriveBL] = bl;
}

void DriveForward (int speed) {
	Drive (speed, speed, speed, speed);
}

void Stop() {
	DriveForward(0);
}

void DriveBackwards (int speed) {
	DriveForward (-speed);
}

void DriveLeft (int speed) {
	// We're weighted oddly. In order to make the thing
	// not crab, scale the rear wheels by this constant.
	const float magic = .6;
	Drive (-speed, speed, -speed * magic, speed * magic);
}

void DriveRight (int speed) {
	// We're weighted oddly. In order to make the thing
	// not crab, scale the rear wheels by this constant.
	const float magic = .45;
	Drive (speed, -speed, speed * magic, -speed * magic);
}

void DriveForwardUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveForward(100);
		wait10Msec (10);
	}
	Stop ();
}

void DriveBackwardsUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveBackwards (75);
		wait10Msec (10);
	}
	Stop ();
}

void DriveLeftUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveLeft (100);
		wait10Msec (10);
	}
	Stop ();
}

void DriveRightUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveRight (100);
		wait10Msec (10);
	}
	Stop ();
}

void DriveDiagonalUntilTicks(const int ticks) {
	while(EncoderTicks() < ticks) {
		Drive(0,100,0,73);
	}
}


void initializeRobot() {
	ClearTimer (T1);
	//orientation = Heading ();
	servo[autoArm] = 127;
	servo[USServo] = SERVO_DEGREES_FRONT;
}

const int TICKS_PER_M = 16000;

void do_left_test () {
	ZeroEncoders ();
	DriveLeftUntilTicks (TICKS_PER_M);
	wait10Msec(100);
	ZeroEncoders();
	//DriveRightUntilTicks(TICKS_PER_M);
}

void do_fwd_test () {
	ZeroEncoders ();
	DriveForwardUntilTicks (TICKS_PER_M);
	wait10Msec (100);
	ZeroEncoders ();
	DriveBackwardsUntilTicks (TICKS_PER_M);
}

void do_diagonal_FL() {
	ZeroEncoders();
	DriveDiagonalUntilTicks(TICKS_PER_M / 4);
}

task main () {
	initializeRobot ();
	//waitForStart();

	//do_fwd_test();

	do_left_test();

	//do_diagonal_FL();

}
