#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     LEGOLIGHT,             sensorLightActive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DriveBL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DriveFR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     FRM,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     EG1,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     EG2,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    USServo,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    autoArm,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "TeleOp_functions.h"  // an H file that we wrote implementing various functions
#include "autonomous_functions.h"	// an H file that we wrote implementing various functions
#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "hitechnic-irseeker-v2.h"
#include "lego-light.h"


const tMotor DriveMotors[] = { DriveFL, DriveBL, DriveFR, DriveBR };  //an array that describes the Drive motors
const int N_MOTORS = 4;

const tMUXSensor FRONTUS = msensor_S4_1;
const tMUXSensor AFT_US = msensor_S4_2;
const tMUXSensor IR = msensor_S4_3;
//const tMUXSensor Gyro = msensor_S4_4;

int SERVO_DEGREES_FRONT = 0;

void  ZeroEncoders ()
{ for (int i = 0; i < N_MOTORS; ++i)
		nMotorEncoder[DriveMotors[i]] = 0;
}

int   EncoderTicks ()
{ int sum = 0;
	for (int i = 0; i < N_MOTORS; ++i)
		sum += abs(nMotorEncoder[DriveMotors[i]]);
	return sum;
}

int   IRSensorRegion () { return HTIRS2readACDir(IR); }

int ReturnLightVal () { return SensorValue[LEGOLIGHT]; }

int FrontUSDistance(int degrees) {
	int dist = 0;
	if(ServoValue[USServo] != degrees) {
		servo[USServo] = degrees;
		wait1Msec(1000);
	}
	dist = USreadDist(FRONTUS);
	return dist;
}

int BackUSDistance() { return USreadDist(AFT_US); }

void Drive(float fl, float fr, float br, float bl) {
	motor[DriveFL] = fl;
	motor[DriveFR] = fr;
	motor[DriveBR] = br;
	motor[DriveBL] = bl;
}

void DriveForward (int speed) {
	Drive (speed, speed * 0.68, speed * 0.68, speed);
}

void DriveBackwards (int speed) {
	DriveForward (-speed);
}

void DriveLeft (int speed) {
	// We're weighted oddly. In order to make the thing
	// not crab, scale the rear wheels by this constant.
	const float magic = .6;
	Drive (-speed, speed, -speed * magic, speed * magic);
}

void DriveRight (int speed) {
	// We're weighted oddly. In order to make the thing
	// not crab, scale the rear wheels by this constant.
	const float magic = .45;
	Drive (speed, -speed, speed * magic, -speed * magic);
}

void Stop () {
	DriveForward (0);
}

void DriveForwardUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveForward (25);
		wait10Msec (10);
	}
	Stop ();
}

void DriveBackwardsUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveBackwards (25);
		wait10Msec (10);
	}
	Stop ();
}

void DriveFBCompensate(int ticks) {
	while(EncoderTicks() > ticks) {
		DriveBackwards(25);
	}

	while(EncoderTicks() < ticks) {
		DriveForward(25);
	}
	Stop();
}

void DriveLeftUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveLeft (100);
		wait10Msec (10);
	}
	Stop ();
}

void DriveRightUntilTicks (const int ticks) {
	while (EncoderTicks () < ticks) {
		DriveRight (100);
		wait10Msec (10);
	}
	Stop ();
}

void DriveDiagonalUntilTicks(const int ticks) {
	while(EncoderTicks() < ticks) {
		Drive(0,100,0,73);
	}
}

void DriveForwardUntilTicksOrIR (const int ticks)
{
	while (EncoderTicks () < ticks &&	5 != IRSensorRegion ())
	{	DriveForward (25);
		wait10Msec (10);
	}
	Stop ();
}


void DriveForwardUntilTicksOrFrontUS(int ticks, int front) {
	while(EncoderTicks() < ticks && FrontUSDistance(SERVO_DEGREES_FRONT) > front) {
		DriveForward(25);
	}
	Stop();
}

void DriveLeftUntilTicksOrColor(int ticks) {
	LSsetActive(LEGOLIGHT);
	while(EncoderTicks() < ticks && ReturnLightVal() < 40) {
		DriveLeft(100);
	}
	if(ReturnLightVal() > 40) {
		PlaySound(soundFastUpwardTones);
	}
	Stop();
}


void Dump () {
	//int initial = servo[autoArm];

	int dump = 0;
	int back = 255;
	servo[autoArm] = dump;
	wait10Msec(250);
	servo[autoArm] = back;
	wait10Msec(150);
}


void DumpCR () {
	//int initial = servo[autoArm];

	servo[autoArm] = 0;
	wait1Msec(1400);
	servo[autoArm] = 255;
	wait1Msec(1400);
	servo[autoArm] = 127;
	wait1Msec(10);
}


void initializeRobot() {
	ClearTimer (T1);
	//orientation = Heading ();
	servo[autoArm] = 127;
	servo[USServo] = SERVO_DEGREES_FRONT;
}

const int TICKS_PER_M = 16000;

void do_main()
{
	ZeroEncoders ();

	float bin1_ticks = 0.53 * TICKS_PER_M;
	float bin2_ticks = 0.83 * TICKS_PER_M;
	float bin3_ticks = 1.40 * TICKS_PER_M;
	float bin4_ticks = 1.72 * TICKS_PER_M;
	float tolerance = 0.15 * TICKS_PER_M;

	float final_fwd_ticks = 1.72 * TICKS_PER_M;

	float diagonal_ticks = 0.50 * TICKS_PER_M;

	float left_ticks = 0.85 * TICKS_PER_M;
	float back_ticks = 1.25 * TICKS_PER_M;

	//Drive forwards until IR beacon or encoder limit
	DriveForwardUntilTicksOrIR (bin4_ticks);

	//If IR is first bin, compensate, dump
	if(EncoderTicks() > bin1_ticks - tolerance && EncoderTicks() < bin1_ticks + tolerance) {
		DriveFBCompensate(bin1_ticks);
		DumpCR ();
	}

	//If IR is second bin, compensate, dump
	else if(EncoderTicks() > bin2_ticks - tolerance && EncoderTicks() < bin2_ticks + tolerance) {
		DriveFBCompensate(bin2_ticks);
		DumpCR();
	}

	//If IR is third bin, compensate, dump
	else if(EncoderTicks() > bin3_ticks - tolerance && EncoderTicks() < bin3_ticks + tolerance) {
		DriveFBCompensate(bin3_ticks);
		DumpCR();
	}

	//If IR is fourth bin or encoder limit, comensate, dump
	else if(EncoderTicks() > bin4_ticks - tolerance && EncoderTicks() < bin4_ticks + tolerance) {
		DriveFBCompensate(bin4_ticks);
		DumpCR();
	}

	//OLD RAMP ISHT
	//Drive forwards to endpoint or front US sensor distance
	DriveForwardUntilTicksOrFrontUS(final_fwd_ticks, 29);

	ZeroEncoders();
	DriveDiagonalUntilTicks(diagonal_ticks);
	wait1Msec(100);
	Drive(100,0,0,100);
	wait1Msec(125);
	Stop();

	ZeroEncoders();
	DriveLeftUntilTicks(left_ticks);

	ZeroEncoders();
	DriveBackwardsUntilTicks(back_ticks);

	//ZeroEncoders ();
	//DriveLeftUntilTicks(0.3 * TICKS_PER_M);
	//while(EncoderTicks() < 0.5913 * TICKS_PER_M && BackUSDistance() == 255) {
	//	writeDebugStreamLine("Dist: %i", EncoderTicks());
	//	DriveLeft(100);
	//}
	//Stop();

	//int distance = TICKS_PER_M / (EncoderTicks() * 0.73025);

	/*
	ZeroEncoders ( );
	wait1Msec(500);
	DriveBackwardsUntilTicks (back_ticks);
	*/
}

task main () {
	initializeRobot ();
	//waitForStart();
	do_main ();
}
