#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DriveFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     DriveBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(servo,  srvo_S1_C4_1,    servo1,               tservoNone)
#pragma config(servo,  srvo_S1_C4_2,    hand,                 tservoStandard)
#pragma config(servo,  srvo_S1_C4_3,    hand2,                tservoStandard)
#pragma config(servo,  srvo_S1_C4_4,    servo4,               tservoNone)
#pragma config(servo,  srvo_S1_C4_5,    servo5,               tservoNone)
#pragma config(servo,  srvo_S1_C4_6,    servo6,               tservoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messagesvalidateLongAddresvalidateLongAddresvalidateLongAddresvalidateLongAddress
#include "TeleOp_functions.h"

const tMotor DriveMotors[] = { DriveFL, DriveFR, DriveBL, DriveBR };
int handPos = 0;

void initializeRobot() {
	servo[hand] = handPos;
	servo[hand2] = 180-ServoValue[hand];

}

task main()
{
	initializeRobot();
		waitForStart();
	while (true)
	{
		omni_drive(DriveMotors);
		operate_flag_claw(flag);
		operate_arm_motor(Arm);
		operate_arm_hand(hand,hand2);


	}
}
