#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     gyro,           sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DriveFL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DriveBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     FRM,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     EG1,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     EG2,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    spiny,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messagesvalidateLongAddresvalidateLongAddresvalidateLongAddresvalidateLongAddress
#include "TeleOp_functions.h"  // an H file that we wrote implementing various functions

const tMotor DriveMotors[] = { DriveFL, DriveFR, DriveBL, DriveBR };  //an array that describes the Drive motors
int handPos = 0; //establishes a variable "handPos" and sets the value of it to 0
int sideSelect = 3;  //establishes a variable "sideSelect" and sets the value of it to 3

void initializeRobot() {                         //Creates a function that is named "initializeRobot"

}

task main()
{
	initializeRobot();
	waitForStart();
	while (true)
	{
		getJoystickSettings(joystick);

		operate_flag_claw(Lift);
		operate_arm_hand(spiny);
		smart_omni_drive(DriveMotors, gyro);

	}
}
