#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     DriveFL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     DriveBL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DriveFR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DriveBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     FRM,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     EG1,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     EG2,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    autoArm,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    spinny,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messagesvalidateLongAddresvalidateLongAddresvalidateLongAddresvalidateLongAddress
#include "TeleOp_functions.h"  // an H file that we wrote implementing various functions
#include "autonomous_functions.h"	// an H file that we wrote implementing various functions
#include "hitechnic-sensormux.h"


const tMotor DriveMotors[] = { DriveFL, DriveBL, DriveFR, DriveBR };  //an array that describes the Drive motors
const int N_MOTORS = 4;

static int orientation = 0;

void initializeRobot()
{ ClearTimer (T1);
  servo[autoArm] = 255;
  orientation = Heading ();
}

long  Time ()          { return time1[T1]; }
float Heading ()       { return compassBearing (Time (), gyro); }

void DriveAtHeading (float heading)
{ float current = Heading ();
  float off = orientation - current;
  omnimove_in_direction (heading + off, DriveMotors, 0);
}

void DriveAtHeadingForTime (float heading, int seconds)
{ int msec = seconds * 1000;
  while (msec > 0)
    { DriveAtHeading (heading);
      wait1Msec (100);
      msec -= 100;
    }
}

void Stop ()
{ for (int i = 0; i < N_MOTORS; ++i)
    motor[DriveMotors[i]] = 0;
}

task main ()
{ initializeRobot ();
  waitForStart ();
  float initial_heading = Heading ();
  DriveAtHeadingForTime (initial_heading, 2);
  DriveAtHeadingForTime (initial_heading + 90, 2);
  DriveAtHeadingForTime (- initial_heading, 2);
  DriveAtHeading (initial_heading - 90, 2);
  Stop ();
}
